
development:
  adapter: postgresql
  encoding: unicode
  database: pdo_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: pdo_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: pdo_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres
